serveurlistenport: "6666"

file-path:
  socketpath: "/opt/vaultaire/vaultaire.sock"
  privatekeypath: "/opt/vaultaire/.ssh/private_key.pem"
  publickeypath: "/opt/vaultaire/.ssh/public_key.pub"
  privatekeyforlogintoclient: "/opt/vaultaire/.ssh/private_key_for_login_client_rsa"
  publickeyforlogintoclient: "/opt/vaultaire/.ssh/private_key_for_login_client_rsa.pub"
  clientconfpath: "/opt/vaultaire/"
  logpath: "/var/log/vaultaire/"
  servercheckonlinetimer: 5

ldap:
  ldap_enable: true
  ldaps_enable: true
  ldap_debug: true
  ldap_port: 389
  ldaps_port: 636

dns:
  dns_enable: true

database:
  username: root
  password: root
  ip_database: "vaultaire-db"
  port_database: "3306"
  databaseName: "vaultaire"

website:
  website_enable: true
  website_port: 443

automatisation:
  sh_folder_path: "/opt/vaultaire/automatisation/"

api:
  api_enable: true
  api_port: 6643

debug:
  debug: true

administreur:
  enable: true
  username: admin
  password: admin123 
  public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCm85Bflch3N5E+zOKapQAn6dipdKgj4oeAorbQV9j4bLUJnFvZ8sfvIGVc0gB5oQEv2Vh1A6lqGNK/CrcgZj5ybNoEwxdbkQyRYkJ6NmtxDs1zLyRUr5GCGtjX44JNNnTDdL+E00Aiw8nFBJRlHkV78ehG62p2DeeVLUydnlnT5ey3KJtmY+Tc0dq5AqWdnAsLbZ/JHw/EuZTeifYJ6wmpxp69oHnsvRxBomH2wSp7CjeYTaBpVFF4KChBSXm/gO4quWQT0JBsDyNmPhZ/QwRJKqujh1B5OX6bbKAl5MOC3OoPXfYkyhilaMku9lK5E6i3wLdP08FQ6Op/Psy7ukTTvMduhqsauxZMMx+x12RAT72LFySZ6RSkLKQXhwkO8pG4laNKFQbDoTULC973AKy0le2Jyb7SnNBL+I+KviMojItYCc6QmQ39TVowy6VQimHiPPs6UPTDt8KROm1SEtPSXj7QvtwJU5hbAG9uFVH/udX7y6BhNPkOgCmrH9s5fh0= root@NTFS"