name: Vaultaire CI

on:
  pull_request:
    branches:
      - dev

jobs:
  build_test_serveur:
    runs-on: ubuntu-latest
    name: Build & Test Serveur
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.9

      - name: Download dependencies
        working-directory: ./src/vaultaire_serveur
        run: go mod download

      - name: Run gofmt check
        working-directory: ./src/vaultaire_serveur
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "Code is not properly formatted. Please run 'go fmt ./...'"
            exit 1
          fi
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/local/bin v1.53.3
        working-directory: ./src/vaultaire_serveur
  
      - name: Run golangci-lint
        run: |
          ./bin/golangci-lint run --out-format=github-actions
        working-directory: ./src/vaultaire_serveur

      - name: Run tests
        working-directory: ./src/vaultaire_serveur
        run: go test -v ./...

      - name: Build binaries
        working-directory: ./src/vaultaire_serveur
        run: go build -v ./...

  build_test_client:
    runs-on: ubuntu-latest
    name: Build & Test Client CLI
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.9

      - name: Download dependencies
        working-directory: ./src/vaultaire_client
        run: go mod download

      - name: Run gofmt check
        working-directory: ./src/vaultaire_client
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "Code is not properly formatted. Please run 'go fmt ./...'"
            exit 1
          fi

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/local/bin v1.53.3
        working-directory: ./src/vaultaire_client

      - name: Run golangci-lint
        run: |
          ./bin/golangci-lint run --out-format=github-actions
        working-directory: ./src/vaultaire_client

      - name: Run tests
        working-directory: ./src/vaultaire_client
        run: go test -v ./...

      - name: Build binaries
        working-directory: ./src/vaultaire_client
        run: go build -v ./...

  build_test_cli:
    runs-on: ubuntu-latest
    name: Build & Test Vaultaire CLI (si diff√©rent)
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.9

      - name: Download dependencies
        working-directory: ./src/vaultaire_cli
        run: go mod download

      - name: Run gofmt check
        working-directory: ./src/vaultaire_cli
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "Code is not properly formatted. Please run 'go fmt ./...'"
            exit 1
          fi

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/local/bin v1.53.3
        working-directory: ./src/vaultaire_cli

      - name: Run golangci-lint
        run: |
          ./bin/golangci-lint run --out-format=github-actions
        working-directory: ./src/vaultaire_cli

      - name: Run tests
        working-directory: ./src/vaultaire_cli
        run: go test -v ./...

      - name: Build binaries
        working-directory: ./src/vaultaire_cli
        run: go build -v ./...
